apiVersion: v1
kind: Service
metadata:
  name: iot-temp-mgmt-service
spec:
  selector:
    app: iot-temp-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
