CREATE TABLE temperature_records
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_name VARCHAR(255),
    location    VARCHAR(255),
    temperature DOUBLE PRECISION,
    time        TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_temperature_records PRIMARY KEY (id)
);

CREATE INDEX idx_temperaturerecord_device_name ON temperature_records (device_name);

CREATE INDEX idx_temperaturerecord_location ON temperature_records (location);